# docs/_config.yml

title: My Amazing Recipe Book
description: A collection of my favorite recipes.
url: "https://recipes.kyle-dixon.com"
baseurl: ""

# https://pages.github.com/themes/
remote_theme: sujaykundu777/devlopr-jekyll
plugins:
  - jekyll-remote-theme

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - .gitattributes